server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
     config:
       server:
           native:
              searchLocations:  classpath:configs/ 

management.endpoints.web.exposure.include: "*"
management.endpoint.health.show-details: always
